### ISSUE TITLE
കിട്ടും-ഡോട്ട്-കോം-എപ്പോ-കിട്ടും.com

### ISSUE THREAD

**Issue by JinsoRaj** [subins2000/kittum.com#3]
അടിച്ചുപോയോ 🥲 ?

**Comment by subins2000** [comment]
https://കിട്ടും-ഡോട്ട്-കോം-എപ്പോ.കിട്ടും.com

ഈ നോഡ് JS ഇത്തിരി അലമ്പാണ്. ചുമ്മാ ക്രാഷായി പോവുന്ന്. ഇപ്പോൾ പുനരാരംഭിച്ചിട്ടുണ്ട്.

**Comment by subins2000** [comment]
നോഡ് JS എടുത്ത് തോട്ടിൽ കളഞ്ഞ് ഗോ എടുത്ത് കയറ്റിയിട്ടുണ്ട്, ഇനി ഒരിക്കലും സൈറ്റ് ക്രാഷ് ആവൂലാ
