### ISSUE TITLE
ഉപയോഗം താൾ

### ISSUE THREAD

**Issue by subins2000** [subins2000/kittum.com#7]
എങ്ങനെ കിട്ടും.com ഉപയോഗിക്കാം എന്ന് വിവരിക്കുന്ന ഒരു താൾ ആവശ്യമാണ്.

**Comment by richardshaju** [comment]
ആ താൾ അങ്ങനെ തെയ്യാറാക്കണം എന്ന് വിവരിക്കുമോ.

**Comment by subins2000** [comment]
@richardshaju നമ്മൾ സാധാരണ About താൾ കാണൂലേ, അതുപോലെ. ഇപ്പോ നമുക്ക് https://കിട്ടും.com/create ഇങ്ങനെ ഒരു താൾ ഉണ്ട്, അതിൽ copy ബട്ടൺ അമർത്തിയാ alert box ആണ് വരുന്നത്, അത് മാറ്റണം, ഒരു ചെറിയ ടെക്സ്റ്റ് കാണിക്കേണ്ടതേ ഉള്ളൂ, alert ഇത്തിരി അനോയിങ്ങ് ആവും കുറച്ച് കഴിഞ്ഞാൽ.

**Comment by richardshaju** [comment]
ഒന്നു സഹായിക്കുമോ, ഒരു ദിവസം ആയി....  

`go run . `
![Screenshot 2023-12-11 165701](https://github.com/subins2000/kittum.com/assets/108459152/d50df879-f85c-4125-800f-af4ba6c4c7ab)

**Comment by subins2000** [comment]
@richardshaju Which operating system? Might not properly work in Windows I think, maybe try in WSL

**Comment by richardshaju** [comment]
Windows. I tried in WSL but the result is same 
Here is the code : 
![Screenshot 2023-12-13 002355](https://github.com/subins2000/kittum.com/assets/108459152/a7a86d47-ee7f-456f-942a-97bff03db52c)
