### ISSUE TITLE
ലിങ്ക് ഉണ്ടാക്കാൻ വേണ്ടി ഒരു താൾ നന്നായിരിക്കും

### ISSUE THREAD

**Issue by subins2000** [subins2000/kittum.com#8]
ഒരു ഇൻപുട്ട് ബോക്സ്, അതിൽ മലയാളം അടിക്കാം, അടിച്ച് കഴിഞ്ഞാൽ ലിങ്ക് പകർത്താൻ കഴിയുന്ന ഒരു ബട്ടൺ കൂടി. ഇതെല്ലാം കിട്ടും.com പ്രധാന താളിലും.

ഈ ഡൊമൈൻ രെജിസ്റ്റർ ചെയ്യുമ്പോൾ ഉള്ള ഇൻപുട്ട് ബോക്സ് പോലെ

`<placeholder-separated-by-dash>.കിട്ടും.com`

**Comment by Jobin-S** [comment]
ഞാൻ ചെയാം,  ഹോം  പേജിൽ ചെയ്യണമോ അതോ പുതിയ പേജ് വേണോ

**Comment by subins2000** [comment]
@Jobin-S പുതിയ താൾ ആയിക്കോട്ടേ, ഉറവിടം എന്ന താഴത്തേ ലിങ്കിന്റെ താഴെ "ലിങ്കുണ്ടാക്കൂ" എന്ന് ഒരു ലിങ്ക് ക്ലിക്ക് ചെയ്യുമ്പോൾ ഈ പുതിയ താളിലേക്ക് പോകട്ടേ

**Comment by subins2000** [comment]
Done via #10
