### ISSUE TITLE
`NET::ERR_CERT_DATE_INVALID`

### ISSUE THREAD

**Issue by VishnuSanal** [subins2000/kittum.com#9]
Hi!

![SS](https://user-images.githubusercontent.com/50027064/221370122-56a0fd3a-d5a5-4538-8228-a62c7e4dd93c.png)

Seems like the SSL Certificate got expired ):

![SS2](https://user-images.githubusercontent.com/50027064/221370338-83ba812f-85d3-45f6-963e-f932f4be40be.png)

**Comment by subins2000** [comment]
This has been fixed and will never happen because we moved it to caddy web server from nginx. cc Thanks to @asdofindia
